FROM python:3.12

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000 8001

RUN echo "File structure of /app:" && /app || ls -R /app

CMD ["python", "counter.py"]