services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - ENV=production
    networks:
      - monitoring_default

networks:
  monitoring_default:
    external: true